---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-adoptopenjdk-hotspot-jre-tarball-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - hotspot
      - jre
      - adoptopenjdk_fallback

  - name: test-aws-ubuntu18-adoptopenjdk-openj9-jdk-tarball-11
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jdk
      - adoptopenjdk_fallback

  - name: test-aws-Debian9-adoptopenjdk-hotspot-jdk-repositories-11
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jdk
      - repositories

  - name: test-aws-centos8-adoptopenjdk-openj9-jre-repositories-11
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - openj9
      - jre
      - repositories

  - name: test-aws-centos7-adoptopenjdk-local-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - local

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      adoptopenjdk:
        java_distribution: adoptopenjdk
        java_major_version: 11
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      openj9:
        adoptopenjdk_impl: openj9
      hotspot:
        adoptopenjdk_impl: hotspot
      adoptopenjdk_fallback:
        transport: adoptopenjdk-fallback
      repositories:
        transport: repositories
      local:
        transport: local
        transport_local: /tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-adoptopenjdk-11/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-adoptopenjdk-11
verifier:
  name: ansible
  lint:
    name: ansible-lint
