---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-adoptopenjdk-hotspot-jdk-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - hotspot
      - jdk

  - name: test-aws-ubuntu18-adoptopenjdk-hotspot-jdk-11
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jdk

  - name: test-aws-Debian9-adoptopenjdk-hotspot-jdk-11
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jdk

  - name: test-aws-centos7-adoptopenjdk-hotspot-jre-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - hotspot
      - jre

  - name: test-aws-ubuntu18-adoptopenjdk-hotspot-jre-11
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jre

  - name: test-aws-Debian9-adoptopenjdk-hotspot-jre-11
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jre

  - name: test-aws-centos7-adoptopenjdk-openj9-jdk-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - openj9
      - jdk

  - name: test-aws-ubuntu18-adoptopenjdk-openj9-jdk-11
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jdk

  - name: test-aws-Debian9-adoptopenjdk-openj9-jdk-11
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jdk

  - name: test-aws-centos7-adoptopenjdk-openj9-jre-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - openj9
      - jre

  - name: test-aws-ubuntu18-adoptopenjdk-openj9-jre-11
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jre

  - name: test-aws-Debian9-adoptopenjdk-openj9-jre-11
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jre

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      adoptopenjdk:
        java_distribution: adoptopenjdk
        transport: adoptopenjdk-fallback
        java_major_version: 11
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      openj9:
        adoptopenjdk_impl: openj9
      hotspot:
        adoptopenjdk_impl: hotspot
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/provisioning/AWS/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-adoptopenjdk-11
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
