---
- name: Prepare Debian
  hosts: debian_family
  tasks:

    - name: Add universe repository for bionic
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'
      become: true

    - name: Install python packages
      apt:
        name: >-
          {{ (ansible_facts.python.version.major|int == 3 )
            | ternary('python3-setuptools', 'python-setuptools') }}
        state: present
      register: status
      until: status is succeeded
      become: true

- name: Prepare RHEL
  hosts: rhel_family
  tasks:

    - name: Enable EPEL repository
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
          {{ ansible_distribution_major_version }}.noarch.rpm"
        state: 'present'
      register: status
      retries: 10
      delay: 5
      until: status is succeeded
      become: true

    - name: Add python-dnf
      yum:
        name: >-
          {{ (ansible_facts.python.version.major|int ==3 )
            | ternary('python3-dnf', 'python-dnf') }}
        state: 'present'
      register: status
      retries: 10
      delay: 5
      until: status is succeeded
      become: true

- name: Prepare host to S3 transport
  hosts: localhost
  gather_facts: true
  vars:
    transport_s3_bucket: java-molecule-s3-test
    transport_s3_path: /java/adoptopenjdk/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz
    java_download_path: /tmp
  tasks:
    - name: Download artifact from s3
      aws_s3:
        bucket: '{{ transport_s3_bucket }}'
        object: '{{ transport_s3_path }}'
        dest: '{{ java_download_path }}/{{ transport_s3_path | basename }}'
        mode: get
        overwrite: different
      retries: 5
      delay: 2
