---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-windows2016-openjdk-11-chocolatey
    aws_image_id: ami-0a125a00b5b736e77
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: true
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-314c223d
    groups:
      - windows
      - chocolatey

  - name: test-aws-windows2019-openjdk-11-chocolatey
    aws_image_id: ami-03ad37b4adab50a4c
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: true
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-314c223d
    groups:
      - windows
      - chocolatey

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      chocolatey:
        java_distribution: openjdk
        transport: chocolatey
        java_major_version: 11
        java_minor_version: 0.4
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify_win.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows-openjdk11-chocolatey
verifier:
  name: ansible
  lint:
    name: ansible-lint
