---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-java-8-jdk-rpm
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - jdk
  - name: test-docker-centos7-java-8-jre-rpm
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - jre

provisioner:
  name: ansible
  inventory:
    group_vars:
      jdk:
        java_package: "jdk"
        java_major_version: 8
        java_tarball_install: False
      jre:
        java_package: "jre"
        java_major_version: 8
        java_tarball_install: False
  log: True
  lint:
    name: ansible-lint
scenario:
  name: docker-java-8-package
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8
