---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-sapmachine-jdk-tarball-10
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - sapmachine
      - jdk
      - sapmachine_fallback

  - name: test-aws-centos8-sapmachine-jre-tarball-10
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - sapmachine
      - jre
      - sapmachine_fallback

  - name: test-aws-Debian9-sapmachine-jre-tarball-10
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - sapmachine
      - jre
      - sapmachine_fallback

  - name: test-aws-ubuntu18-sapmachine-jdk-tarball-10
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - sapmachine
      - jdk
      - sapmachine_fallback

  - name: test-aws-ubuntu18-sapmachine-s3-10
    image: ami-012fd5eb46f56731f
    profile_name: epmldi-instance-profile
    platform: ubuntu18
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - sapmachine
      - s3

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      sapmachine:
        java_distribution: sapmachine
        java_major_version: 10
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      sapmachine_fallback:
        transport: sapmachine-fallback
      s3:
        transport: s3
        transport_s3_bucket: java-molecule-s3-test
        transport_s3_path: /java/sapmachine/sapmachine-jdk-10.0.2.13_linux-x64_bin.tar.gz
        transport_s3_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        transport_s3_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-sapmachine-10/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-sapmachine-10
verifier:
  name: ansible
  lint:
    name: ansible-lint
