---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint: |
  set -e
  yamllint -f colored -c .yamllint .
  ansible-lint -c .ansible-lint
platforms:
  - name: test-aws-centos6-oracle_java-7-rpm
    image: ami-1585c46a
    platform: centos6
    instance_type: t2.medium
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.06
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - rpm

  - name: test-aws-Debian9-oracle_java-7-tarball
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.06
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - tarball

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_FILTER_PLUGINS: ../../filter_plugins/
  config_options:
    defaults:
      forks: 30
      callback_whitelist: profile_tasks,timer
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      tarball:
        java_distribution: oracle_java
        java_package: jdk
        java_major_version: 7
        java_tarball_install: true
        transport: web
        transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-7u191-linux-x64.tar.gz"
        java_unlimited_policy_enabled: true
        java_unlimited_policy_transport: oracle-fallback
      rpm:
        java_distribution: oracle_java
        java_package: jdk
        java_major_version: 7
        java_tarball_install: false
        transport: web
        transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-7u191-linux-x64.rpm"
        java_unlimited_policy_enabled: true
        java_unlimited_policy_transport: oracle-fallback
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: cloud-aws-direct-7
verifier:
  name: ansible
