---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-centos8-oracle_java-8-s3-rpm
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: t3.medium
    profile_name: epmldi-instance-profile
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - s3
      - package
      - pip3

  - name: test-aws-centos7-oracle_java-8-s3
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    profile_name: epmldi-instance-profile
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - s3
      - tarball
      - pip2

  - name: test-aws-ubuntu18-oracle_java-8-s3
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    profile_name: epmldi-instance-profile
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - s3
      - tarball
      - pip3

  - name: test-aws-debian9-oracle_java-8-local
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - local
      - tarball
      - pip2

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      pip2:
        pip_executable: pip
        python_executable: python
      pip3:
        pip_executable: pip3
        python_executable: python3
      local:
        transport: local
        transport_local: /tmp/jdk-8u202-linux-x64.tar.gz
      s3:
        transport: s3
        transport_s3_bucket: java-molecule-s3-test
        transport_s3_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        transport_s3_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      tarball:
        java_distribution: oracle_java
        java_package: jdk
        java_tarball_install: true
        transport_s3_path: /java/jdk-8u202-linux-x64.tar.gz
      package:
        java_distribution: oracle_java
        java_package: jdk
        java_tarball_install: false
        transport_s3_path: /java/jdk-8u202-linux-x64.rpm
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct-8
verifier:
  name: ansible
  lint:
    name: ansible-lint
