---
- name: 'Fetch oracle artifact with {{ transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - 'fetch/{{ transport }}.yml'
    - fetch/unknown-transport.yml
  loop_control:
    loop_var: transport_driver

- name: Set java full version
  set_fact:
    java_full_version: '{{ java_major_version }}.{{ java_minor_version }}'

- name: Perform install from artifacts
  block:
    - name: Install requirements
      package:
        name: '{{ requirements }}'
        state: present
      register: installed_packages
      until: installed_packages is succeeded

    - name: 'Perform {{ java_binary_type }} install'
      include_tasks: >-
        Linux/{{ java_tarball_install | ternary('tarball', ansible_os_family) }}.yml

    - name: Find java_folder
      find:
        paths: '{{ java_path }}'
        recurse: False
        file_type: directory
        patterns: '{{ java_folder }}'
        use_regex: True
      register: java_dir

    - name: Set actual java directory
      set_fact:
        java_folder: "{{ java_dir.files | map(attribute='path') | list | last | basename }}"

    - name: Put java profile
      template:
        src: java.sh.j2
        dest: /etc/profile.d/java.sh
        owner: root
        group: root
        mode: 0555

    - name: Check for java binaries existence
      stat:
        path: '{{ java_path }}/{{ java_folder }}/bin/{{ binary }}'
      register: java_binary_collection
      loop:
        - java
        - javac
        - jar
      loop_control:
        loop_var: binary

    - name: Update alternatives
      alternatives:
        name: '{{ java_item.binary }}'
        path: '{{ java_path }}/{{ java_folder }}/bin/{{ java_item.binary }}'
        link: '/usr/bin/{{ java_item.binary }}'
        priority: 100
      when: java_item.stat.exists | bool
      loop: '{{ java_binary_collection.results }}'
      loop_control:
        loop_var: java_item
  become: True

- name: 'Fetch oracle security policy with {{ java_unlimited_policy_transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - 'fetch/security-fetch-{{ java_unlimited_policy_transport }}.yml'
    - fetch/unknown-transport.yml
  loop_control:
    loop_var: transport_driver
  when:
    - java_unlimited_policy_enabled
    - java_full_version is version('8.151', '<')
