---
- name: 'Fetch oracle artifact with {{ transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - 'fetch/{{ transport }}.yml'
    - fetch/unknown-transport.yml
  loop_control:
    loop_var: transport_driver

- name: Set java full version
  set_fact:
    java_full_version: '{{ java_major_version }}.{{ java_minor_version }}'

- name: 'Fetch oracle security policy with {{ java_unlimited_policy_transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - 'security_policy_fetch/{{ java_unlimited_policy_transport }}.yml'
    - security_policy_fetch/unknown-transport.yml
  loop_control:
    loop_var: transport_driver
  when:
    - java_unlimited_policy_enabled
    - java_full_version is version('8.151', '<')

- name: Become section
  block:
    - name: Install requirements
      package:
        name: '{{ requirements }}'
        state: present
      register: installed_packages
      until: installed_packages is succeeded

    - name: Mkdir for java installation
      file:
        path: '{{ java_path }}'
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: 'Install java {{ java_full_version }}'
      unarchive:
        src: '{{ oracle_artifact }}'
        dest: '{{ java_path }}'
        remote_src: True
        owner: root
        group: root
        mode: 0755
        creates: '{{ java_path }}{{ java_package }}1.{{ java_major_version }}.0_{{ java_minor_version }}/bin/'
      when: java_tarball_install | bool

    # Default package installation path /usr/java
    # - name: Intsall java {{ java_full_version }}' rpm / deb
    #   package:
    #     name: '{{ oracle_artifact }}'
    #     state: present
    #   when: not java_tarball_install | bool

    # WORKAROUND
    # - name: Install rpm / deb
    #   command: "rpm -i --badreloc --force --relocate /usr/java/={{ java_path }} {{ oracle_artifact }}"
    #   args:
    #     creates: '{{ java_path }}{{ java_package }}1.{{ java_major_version }}.0_{{ java_minor_version }}-amd64/bin/'
    #   when: not java_tarball_install | bool

    # Default package installation /usr/java
    # install root don't working
    # manual install yum --releasever=/ --installroot=/opt/java install /tmp/jdk-8u201-linux-x64.rpm
    # - name: Install rpm
    #   yum:
    #     name: '{{ oracle_artifact }}'
    #     state: present
    #     installroot: '{{ java_path }}'
    #   when: not java_tarball_install | bool

    - name: Check for java binaries existence
      stat:
        path: '{{ java_path }}{{ java_package }}1.{{ java_major_version }}.0_{{ java_minor_version }}/bin/{{ binary }}'
      register: java_binary_collection
      loop:
        - java
        - javac
        - jar
      loop_control:
        loop_var: binary

    - name: Update alternatives
      alternatives:
        name: '{{ java_item.binary }}'
        path: "{{ java_path }}{{ java_package }}1.{{ java_major_version }}.\
          0_{{ java_minor_version }}/bin/{{ java_item.binary }}"
        link: '/usr/bin/{{ java_item.binary }}'
        priority: 100
      when: java_item.stat.exists | bool
      loop: '{{ java_binary_collection.results }}'
      loop_control:
        loop_var: java_item

    - name: Put java profile
      template:
        src: java.sh.j2
        dest: /etc/profile.d/java.sh
        owner: root
        group: root
        mode: 0555

  become: True
