---
- name: Download artifact from web
  get_url:
    url: '{{ transport_web }}'
    dest: '{{ java_download_path }}'
  register: file_downloaded
  retries: 5
  delay: 2
  until: file_downloaded is succeeded
