---
  - name: 'Fetch root page {{ zulu_root_page }}'
    uri:
      url: '{{ zulu_root_page }}'
      return_content: true
    register: root_page

  - name: Find release url
    set_fact:
      release_url: >-
        {{ root_page['content']
          | regex_findall('(https://cdn.azul.com/zulu/bin/zulu'
            + java_major_version|string
            + '.+' + java_package + '.+-linux_x64.tar.gz)')
        }}

  - name: Find checksum
    set_fact:
      checksum: >-
        {{ root_page['content']
          | regex_findall('Checksum \(MD5\): ([a-z0-9]+).+[\n\w\s<>=":/.-]+' + release_url[0])
        }}

  - name: 'Download artifact from {{ release_url[0] }}'
    get_url:
      url: '{{ release_url[0] }}'
      dest: '{{ java_download_path }}'
      checksum: 'md5:{{ checksum[0] }}'
    register: file_downloaded
    retries: 20
    delay: 5
    until: file_downloaded is succeeded
