---
- name: Fetch download page
  uri:
    url: "{{ zulu_api_page }}/zulu/packages/\
      ?java_version={{ java_major_version }}\
      &os=linux\
      &arch={{ (java_arch == 'x64') | ternary('x64', 'x86') }}\
      &java_package_type={{ java_package }}\
      &latest=true\
      &archive_type=tar.gz\
      &javafx_bundled=false\
      &crac_supported=false"
    return_content: true
    follow_redirects: all
  register: root_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ root_page.json[0].download_url }}

- name: Exit if Zulu version is not found
  fail:
    msg: 'Zulu version {{ java_major_version }} not found'
  when: release_url is not defined

- name: 'Download artifact from {{ release_url }}'
  get_url:
    url: '{{ release_url }}'
    dest: '{{ java_download_path }}/{{ (release_url|urlsplit).path|basename }}'
  register: file_downloaded
  retries: 20
  delay: 5
  until: file_downloaded is succeeded
