---
- name: 'Fetch download page'
  uri:
    url: "{{ zulu_api_page }}\
      /bundles/latest/\
      ?version={{ java_major_version }}\
      &ext=tar.gz&os=linux&\
      arch={{ (java_arch == 'x64') | ternary('x64', 'x86') }}"
    return_content: true
    follow_redirects: all
  register: root_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ (root_page.content | from_json).url }}

- name: Find checksum
  set_fact:
    checksum: >-
      {{ (root_page.content | from_json).md5_hash }}

- name: Exit if Zulu version is not found
  fail:
    msg: 'Zulu version {{ java_major_version }} not found'
  when: release_url is not defined

- name: 'Download artifact from {{ release_url }}'
  get_url:
    url: '{{ release_url }}'
    dest: '{{ java_download_path }}'
    checksum: 'md5:{{ checksum }}'
  register: file_downloaded
  retries: 20
  delay: 5
  until: file_downloaded is succeeded
