---
- name: debug java_artifact
  debug:
    var: java_artifact

- name: debug java_folder_repo_transport
  debug:
    var: java_folder_repo_transport

- name: Install java packages
  apt:
    deb: '{{ java_artifact | default(omit) }}'
    name: '{{ (openjdk_package if transport == "repositories") | default(omit) }}'
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: package_install
  until: package_install is succeeded
