---
- name: Install java packages
  apt:
    deb: '{{ java_artifact | default(omit) }}'
    name: '{{ (jdk_package if transport == "repositories") | default(omit) }}'
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: package_install
  until: package_install is succeeded
