---
- name: Install java packages
  zypper:
    name: '{{ (transport == "repositories") | ternary(jdk_package, java_artifact) }}'
    state: present
  register: package_install
  retries: 20
  delay: 5
  until: package_install is succeeded
