---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:
    # Developer must implement.
    - name: Destroy molecule instance(s)
      epc_vm:
        description: "{{ item.name | default('Molecule_epc_instance') }}"
        access_id: "{{ item.access_id |default(omit) }}"
        token: "{{ item.token | default(omit) }}"
        region: "{{ item.region | default(omit) }}"
        project: "{{ item.project | default(omit) }}"
        instance_id: "{{ item.instance_id | default(omit) }}"
        ignore_ssl: "{{ item.ignore_ssl | default(True) }}"
        wait_timeout: "{{ item.wait_timeout | default(1200) }}"
        state: terminate
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: epc_jobs
      until: epc_jobs.finished
      retries: 300
      delay: 20
      with_items: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        # NOTE(retr0h): Workaround for Ansible 2.2.
        #               https://github.com/ansible/ansible/issues/20885
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
    # Mandatory configuration for Molecule to function.
