---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-windows2016-oracle_java_jre-8-chocolatey
    aws_image_id: ami-0a125a00b5b736e77
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5a.large
    #assign_public_ip: true
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    #vpc_subnet_id: subnet-0da98b31
    groups:
      - windows
      - chocolatey

  - name: test-aws-windows2019-oracle_java_jre-8-chocolatey
    aws_image_id: ami-03ad37b4adab50a4c
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5a.large
    #assign_public_ip: true
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    #vpc_subnet_id: subnet-0da98b31
    groups:
      - windows
      - chocolatey

provisioner:
  name: ansible
  log: false
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      chocolatey:
        java_distribution: oracle_java
        java_package: jre
        transport: chocolatey
        java_major_version: 8
        java_minor_version: 211
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows-jre8-chocolatey
verifier:
  name: testinfra
  lint:
    name: flake8
