---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos8-adoptopenjdk-hotspot-jre-repositories-12
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - hotspot
      - jre
      - repositories
      - pip3

  - name: test-aws-centos7-adoptopenjdk-openj9-jdk-tarball-12
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - openj9
      - jdk
      - adoptopenjdk_fallback
      - pip2

  - name: test-aws-Debian9-adoptopenjdk-openj9-jre-tarball-12
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jre
      - adoptopenjdk_fallback
      - pip2

  - name: test-aws-ubuntu18-adoptopenjdk-hotspot-jdk-repositories-12
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jdk
      - repositories
      - pip3

  - name: test-aws-Debian9-adoptopenjdk-hotspot-jre-repositories-12
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jre
      - repositories
      - pip2

  - name: test-aws-Debian9-adoptopenjdk-s3-12
    image: ami-003f19e0e687de1cd
    profile_name: epmldi-instance-profile
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - s3
      - pip2

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      pip2:
        pip_executable: pip
        python_executable: python
      pip3:
        pip_executable: pip3
        python_executable: python3
        ansible_python_interpreter: /usr/bin/python3
      adoptopenjdk:
        java_distribution: adoptopenjdk
        java_major_version: 12
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      openj9:
        adoptopenjdk_impl: openj9
      hotspot:
        adoptopenjdk_impl: hotspot
      adoptopenjdk_fallback:
        transport: adoptopenjdk-fallback
      repositories:
        transport: repositories
      s3:
        transport: s3
        transport_s3_bucket: java-molecule-s3-test
        transport_s3_path: /java/adoptopenjdk/OpenJDK12U-jdk_x64_linux_hotspot_12.0.1_12.tar.gz
        transport_s3_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        transport_s3_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-adoptopenjdk-12/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-adoptopenjdk-12
verifier:
  name: ansible
  lint:
    name: ansible-lint
