---
- name: Install java packages
  win_package:
    path: '{{ java_artifact }}'
    product_id: '{{ java_product_id }}'
    state: present
    arguments: 'INSTALLDIR={{ java_path }}\{{ java_folder }} INSTALL_SILENT=Enable'
    creates_path: '{{ java_path }}\{{ java_folder }}'
