---
- name: debug java_path
  debug:
    var: java_path

- name: debug java_artifact
  debug:
    var: java_artifact

- name: debug java_folder
  debug:
    var: java_folder

- name: Mkdir for java installation
  win_file:
    path: '{{ java_path }}'
    state: directory

- name: 'Install java {{ java_full_version }}'
  win_unzip:
    src: '{{ java_artifact }}'
    dest: '{{ java_path }}'
    creates: '{{ java_path }}\{{ java_folder }}'
