---
- name: Prepare host to S3 transport
  hosts: localhost
  gather_facts: true
  vars:
    transport_s3_bucket: java-molecule-s3-test
    java_download_path: /tmp
  tasks:
    - name: Download artifact from s3
      aws_s3:
        bucket: '{{ transport_s3_bucket }}'
        object: 'java/jdk-6u45-linux-x64.rpm'
        # dest: '{{ java_download_path }}/jdk-6u45-linux-x64.rpm'
        mode: geturl
      register: s3_link

    - name: debug s3_link
      debug:
        var: s3_link

- name: Converge
  hosts: all
  roles:
    - role: ansible-role-java
