---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos8-openjdk-ga
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: t3.medium
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - centos8

  - name: test-aws-centos7-openjdk-ga
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family

  - name: test-aws-ubuntu18-openjdk-ga
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family

  - name: test-aws-Debian9-openjdk-ga
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family

  - name: test-aws-Debian10-openjdk-ga
    image: ami-0dedf6a6502877301
    platform: debian10
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.05
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family

  - name: test-aws-Amazon-openjdk-ga
    image: ami-035b3c7efe6d061d5
    platform: amazon
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ec2-user
    groups:
      - rhel_family

  - name: test-aws-Amazon2-openjdk-ga
    image: ami-0b898040803850657
    platform: amazon2
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ec2-user
    groups:
      - rhel_family

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      forks: 30
      callback_whitelist: profile_tasks,timer
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-openjdk-ga
verifier:
  name: ansible
  lint:
    name: ansible-lint
