---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AWS/prepare.yml

- name: Prepare RHEL
  hosts: rhel_family
  tasks:

    - block:
        - name: Enable EPEL repository
          yum:
            name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
              {{ ansible_distribution_major_version }}.noarch.rpm"
            state: 'present'
          register: status
          until: status is succeeded
      rescue:
        - name: Enable default EPEL repository
          yum:
            name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            state: 'present'
          register: status
          until: status is succeeded
      become: true

    - name: Install archivers
      yum:
        name:
          - tar
          - unzip
        state: present
      register: status
      until: status is succeeded
      become: true
