---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-windows2019-oracle_java-11-zip
    aws_image_id: ami-03ad37b4adab50a4c
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5a.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - zip

  - name: test-aws-windows2016-oracle_java-11-exe
    aws_image_id: ami-0a125a00b5b736e77
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5a.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - exe

provisioner:
  name: ansible
  log: false
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      zip:
        java_distribution: oracle_java
        java_tarball_install: true
        transport: local
        transport_local: /tmp/jdk-11.0.3_windows-x64_bin.zip
      exe:
        java_distribution: oracle_java
        java_tarball_install: false
        transport: local
        transport_local: /tmp/jdk-11.0.3_windows-x64_bin.exe
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows-11
verifier:
  name: testinfra
  lint:
    name: flake8
