---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-Debian9-adoptopenjdk-hotspot-jdk-tarball-8
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptopenjdk
      - hotspot
      - jdk
      - adoptopenjdk_fallback

  - name: test-aws-ubuntu18-adoptopenjdk-openj9-jre-tarball-8
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - openj9
      - jre
      - adoptopenjdk_fallback

  - name: test-aws-centos7-adoptopenjdk-hotspot-jdk-repositories-8
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptopenjdk
      - hotspot
      - jdk
      - repositories

  - name: test-aws-amazon2-adoptopenjdk-openj9-jre-repositories-8
    image: ami-0b898040803850657
    platform: amazon2
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ec2-user
    groups:
      - rhel_family
      - adoptopenjdk
      - openj9
      - jre
      - repositories

  - name: test-aws-ubuntu18-adoptopenjdk-web-8
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptopenjdk
      - web

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      forks: 30
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      adoptopenjdk:
        java_distribution: adoptopenjdk
        java_major_version: 8
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      openj9:
        adoptopenjdk_impl: openj9
      hotspot:
        adoptopenjdk_impl: hotspot
      adoptopenjdk_fallback:
        transport: fallback
      repositories:
        transport: repositories
      web:
        transport: web
        transport_web: >-
          https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jdk_x64_linux_hotspot_8u212b04.tar.gz
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-adoptopenjdk-8
verifier:
  name: ansible
  lint:
    name: ansible-lint
