---
- name: Prepare host to S3 transport
  hosts: transport_s3
  gather_facts: True
  tasks:
    - name: 'Enable EPEL repository'
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
          {{ ansible_distribution_major_version }}.noarch.rpm"
        state: 'present'
      register: status
      until: status is succeeded
      become: True
      when:
        - ansible_os_family == 'RedHat'
    - name: 'Install pip package'
      package:
        name: "{{ ansible_os_family == 'Ubuntu' | ternary('python-pip','python2-pip') }}"
        state: 'present'
      register: status
      until: status is succeeded
      become: True
    - name: 'Install boto module'
      pip:
        name:
          - 'pip'
          - 'botocore'
          - 'boto'
          - 'boto3'
        state: present
        extra_args: --upgrade
      register: status
      until: status is succeeded
      become: True
