---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-openjdk
    image: leandelivery/docker-systemd:centos7
    privileged: true
    groups:
      - rhel_family
  - name: test-docker-ubuntu1804-openjdk
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint
