---
- name: Mkdir for java installation
  win_file:
    path: '{{ java_path }}'
    state: directory

- name: Unzip java archive
  win_unzip:
    src: '{{ oracle_artifact }}'
    dest: '{{ java_path }}'
    creates: '{{ java_path }}\{{ java_folder }}'
