---
- name: Mkdir for java installation
  win_file:
    path: '{{ java_path }}'
    state: directory

- debug:
    msg: "java_folder={{java_folder}}"

- name: Unzip java archive
  win_unzip:
    src: '{{ java_artifact }}'
    dest: '{{ java_path }}'
    creates: '{{ java_path }}\{{ java_folder }}'
