---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-windows2016-zulu-12
    aws_image_id: ami-00a20f508263efd30
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: true
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-314c223d
    groups:
      - windows
      - zulu

  - name: test-aws-windows2019-zulu-12
    aws_image_id: ami-0477b9335a5a75438
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: true
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-314c223d
    groups:
      - windows
      - zulu

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      zulu:
        java_distribution: zulu
        transport: zulu-fallback
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify_win.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows-zulu-12
verifier:
  name: ansible
  lint:
    name: ansible-lint
