---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-windows2016-oracle_java-12-zip
    aws_image_id: ami-00a20f508263efd30
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - zip

  - name: test-aws-windows2019-oracle_java-12-exe
    aws_image_id: ami-0477b9335a5a75438
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - exe

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      zip:
        java_distribution: oracle_java
        java_tarball_install: true
        transport: local
        transport_local: /tmp/jdk-12.0.1_windows-x64_bin.zip
      exe:
        java_distribution: oracle_java
        java_tarball_install: false
        transport: local
        transport_local: /tmp/jdk-12.0.1_windows-x64_bin.exe
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify_win.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows-12
verifier:
  name: ansible
  lint:
    name: ansible-lint
