---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-windows2016-oracle_java-8-web
    aws_image_id: ami-00a20f508263efd30
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - web

  - name: test-aws-windows2019-oracle_java-8-s3-local
    aws_image_id: ami-03ad37b4adab50a4c
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - local

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      local:
        java_distribution: oracle_java
        transport: local
        java_tarball_install: false
        transport_local: /tmp/jdk-8u202-windows-x64.exe
      web:
        java_distribution: oracle_java
        transport: web
        java_tarball_install: false
        transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u45-windows-x64.exe"
        java_unlimited_policy_transport: oracle-fallback
        java_unlimited_policy_enabled: true
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify_win.yml
scenario:
  name: cloud-aws-windows-8
verifier:
  name: ansible
  lint:
    name: ansible-lint
