---
- name: Prepare host to S3 transport
  hosts: localhost
  gather_facts: True
  vars:
    transport_s3_bucket: java-molecule-s3-test
    transport_s3_path: java/jdk-8u202-windows-x64.exe
    download_path: /tmp
  tasks:
    - name: Download artifact from s3
      aws_s3:
        bucket: '{{ transport_s3_bucket }}'
        object: '{{ transport_s3_path }}'
        dest: '{{ download_path }}/{{ transport_s3_path | basename }}'
        mode: get
        overwrite: different
      retries: 5
      delay: 2

- name: Prepare windows host
  hosts: windows
  gather_facts: True
  tasks:

    - name: Check choco
      win_chocolatey:
        name: all
        state: present

    # Workaround for new chocolatey output.
    # See https://github.com/ansible/ansible/issues/53860#issuecomment-473431360 for more details
    - name: disable enhanced exit codes
      win_chocolatey_feature:
        name: useEnhancedExitCodes
        state: disabled

    - name: 'Install net framework'
      win_chocolatey:
        name: 'dotnet4.6.2'
      register: choco_install
      retries: 15
      delay: 5
      until: choco_install is succeeded

#     - name: Enable strong crypto
#       win_regedit:
#         path: "{{ item }}"
#         name: SchUseStrongCrypto
#         type: dword
#         data: 00000001
#       loop:
#         - HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
#         - HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319

#     - name: reboot windows
#       win_reboot:
#         reboot_timeout: 9000
#         post_reboot_delay: 20
