---
- name: Prepare host to S3 transport
  hosts: localhost
  gather_facts: True
  vars:
    transport_s3_bucket: java-molecule-s3-test
    transport_s3_path: java/jdk-8u202-windows-x64.exe
    download_path: /tmp
  tasks:
    - name: Download artifact from s3
      aws_s3:
        bucket: '{{ transport_s3_bucket }}'
        object: '{{ transport_s3_path }}'
        dest: '{{ download_path }}/{{ transport_s3_path | basename }}'
        mode: get
        overwrite: different
      retries: 5
      delay: 2

    - name: Enable strong crypto
      win_regedit:
        path: "{{ item }}"
        name: SchUseStrongCrypto
        type: dword
        data: 00000001
      loop:
        - HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
        - HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319

    - name: reboot windows
      win_reboot:
        reboot_timeout: 9000
        post_reboot_delay: 20
