---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-epc-centos7-oracle_java_jre
    image: CentOS7_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
      - web_jre
  - name: test-epc-ubuntu1804-oracle_java_jre
    image: Ubuntu18.04_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - debian_family
      - web_jre
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      web_jre:
        java_distribution: oracle_java
        java_package: jre
        java_major_version: 8
        transport: web
        transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-java/jre-8u211-linux-x64.tar.gz"
        java_tarball_install: true
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/provisioning/EPC/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
    verify: ../resources/tests/verify.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-epc-delegated
verifier:
  name: ansible
  lint:
    name: ansible-lint
