---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-java
      java_major_version: 8
      transport: web
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-java/jre-8u202-linux-x64.tar.gz"
