---
- name: Include common prepare
  import_playbook: provisioning/AWS/prepare.yml

- name: Prepare RHEL
  hosts: rhel_family
  tasks:
    - name: 'Enable EPEL repository'
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
          {{ ansible_distribution_major_version }}.noarch.rpm"
        state: 'present'
      register: status
      until: status is succeeded
      become: true

- name: Prepare host to S3 transport
  hosts: s3
  gather_facts: true
  tasks:
    - name: 'Install pip package'
      package:
        name: python-pip
        state: present
      register: status
      until: status is succeeded
      become: true

    - name: 'Install boto module'
      pip:
        name:
          - 'pip'
          - 'botocore'
          - 'boto'
          - 'boto3'
        state: present
        extra_args: --upgrade
      register: status
      until: status is succeeded
      become: true
