---
- name: Prepare Debian
  hosts: debian_family
  tasks:

    - name: Add universe repository for bionic
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'
      become: true

    - name: Install python packages
      apt:
        name: >-
          {{ (ansible_facts.python.version.major|int == 3 )
            | ternary('python3-setuptools', 'python-setuptools') }}
        state: present
      register: status
      until: status is succeeded
      become: true

- name: Prepare RHEL
  hosts: rhel_family
  tasks:

    - block:
        - name: Enable EPEL repository
          yum:
            name: '{{ epel_path }}'
            state: present
          register: status
          retries: 10
          until: status is succeeded
      become: true

- name: Prepare host to S3 transport
  hosts: s3
  tasks:
    - name: Install pip package
      package:
        name: >-
          {{ (ansible_facts.python.version.major|int ==3 )
            | ternary('python3-pip', 'python-pip') }}
        state: present
      register: status
      retries: 10
      until: status is succeeded
      become: true

    - name: Install boto module
      pip:
        name:
          - botocore
          - boto
          - boto3
        state: present
        executable: >-
          {{ (ansible_facts.python.version.major|int ==3 )
            | ternary('pip3', 'pip') }}
        extra_args: --upgrade
      register: status
      until: status is succeeded
      become: true
