---
- name: 'Download artifact from {{ artifact_url }}'
  win_get_url:
    url: '{{ artifact_url }}'
    dest: '{{ java_download_path }}\{{ artifact_basename }}'
    force: true

- name: 'Get {{ checksum_alg }} checksum of file'
  win_stat:
    path: '{{ java_download_path }}\{{ artifact_basename }}'
    get_checksum: true
    checksum_algorithm: '{{ checksum_alg }}'
  register: artifact
