---
- name: Copy artifact to destination
  win_copy:
    src: '{{ transport_local }}'
    dest: '{{ java_download_path }}\'
  register: file_downloaded
  retries: 5
  delay: 2
  until: file_downloaded is succeeded
