---
- name: Download artifact from web
  win_get_url:
    url: '{{ transport_web }}'
    dest: >-
      {{ java_download_path }}\{{ (transport_web | urlsplit('path')).split('/')[-1] }}
    force: false
  register: file_downloaded
  retries: 5
  delay: 2
  until: file_downloaded is succeeded
