---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-java-8-jdk
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - jdk
  - name: test-docker-ubuntu1804-java-8-jdk
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - jdk
  - name: test-docker-centos7-java-8-jre
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - jre
  - name: test-docker-ubuntu1804-java-8-jre
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - jre
  - name: test-docker-centos7-java-8-server-jre
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - server_jre
  - name: test-docker-ubuntu1804-java-8-server-jre
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - server_jre
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
scenario:
  name: docker-java-8
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8
