---
- name: Unzip patch file
  win_unzip:
    src: '{{ security_policy_oracle_artifact }}'
    dest: '{{ java_act_path }}\jre\lib\security\'
    creates: '{{ java_act_path }}\jre\lib\security\{{ security_patch_folders[java_major_version|int] }}'

- name: Apply patch file
  win_copy:
    src: '{{ java_act_path }}\jre\lib\security\{{ security_patch_folders[java_major_version|int] }}\{{ policy_item }}'
    dest: '{{ java_act_path }}\jre\lib\security\'
    remote_src: True
  loop:
    - local_policy.jar
    - US_export_policy.jar
  loop_control:
    loop_var: policy_item

- name: 'Apply setting'
  win_lineinfile:
    path: '{{ java_act_path }}\jre\lib\security\java.security'
    line: 'crypto.policy=unlimited'
