---
# - name: Copy patch file
#   win_copy:
#     src: '{{ security_policy_oracle_artifact }}'
#     dest: 'C:\Program Files\Java\{{ security_policy_oracle_artifact|basename }}'
#     force: True

- name: Unzip patch file
  win_unzip:
    src: '{{ security_policy_oracle_artifact }}'
    dest: '{{ java_act_path }}\jre\lib\security\'
    creates: '{{ java_act_path }}\jre\lib\security\{{ security_patch_folders[java_major_version|int] }}'
  register: jce_res
        # C:\Program Files\Java\{{
        #     security_policy_oracle_artifact|basename
        #       }}\jre{{ java_major_version }}\lib\security\

- name: debug
  debug:
    var: jce_res

- name: Find java_folder
  win_find:
    paths: '{{ java_act_path }}\jre\lib\security\{{ security_patch_folders[java_major_version|int] }}'
    recurse: True
    file_type: file
    patterns: '*'
    # use_regex: True
  register: java_dir

- name: debug
  debug:
    var: java_dir

# - name: Apply patch file
#   win_command:
#     'xcopy -r C:\\Program Files\\Java\\jre{{ java_major_version }}\\lib\\security\\\
#     {{ security_patch_folders[java_major_version|int] }}/*.jar \
#     C:\Program Files\\Java\\jre{{ java_major_version }}\\lib\\security\\'
#   args:
#     removes: 'C:\\Program Files\\Java\\jre{{ java_major_version }}\\lib\\security\\\
#       {{ security_patch_folders[java_major_version|int] }}\\local_policy.jar'

# - name: 'Apply setting'
#   win_lineinfile:
#     path: 'C:\\Program Files\\Java\\jre1.{{ java_major_version }}.0_\
#            {{ java_minor_version }}\\lib\\security\\java.security'
#     regexp: '#crypto.policy=unlimited'
#     line: 'crypto.policy=unlimited'
