---
- name: Install java packages
  apt:
    deb: '{{ oracle_artifact }}'
    state: present
  register: package_install
  until: package_install is succeeded

- name: Check for java binaries existence
  stat:
    path: '{{ java_path }}/{{ java_folder }}/bin/{{ binary }}'
  register: java_binary_collection
  loop:
    - java
    - javac
    - jar
  loop_control:
    loop_var: binary

- name: Update alternatives
  alternatives:
    name: '{{ java_item.binary }}'
    path: '{{ java_path }}/{{ java_folder }}/bin/{{ java_item.binary }}'
    link: '/usr/bin/{{ java_item.binary }}'
    priority: 100
  when: java_item.stat.exists | bool
  loop: '{{ java_binary_collection.results }}'
  loop_control:
    loop_var: java_item
