---
- name: Install java packages
  apt:
    deb: '{{ oracle_artifact | default(omit) }}'
    name: '{{ openjdk_package | default(omit) }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: package_install
  until: package_install is succeeded
