---
- name: Perform install from repositories
  block:
    - name: 'Perform repo install'
      include_tasks: '{{ install_task }}'
      with_first_found:
        - 'install/{{ ansible_distribution }}_{{ ansible_distribution_version }}_{{ java_distribution }}_{{ java_major_version }}.yml'
        - 'install/{{ ansible_os_family }}_{{ java_distribution }}.yml'
        - 'install/{{ ansible_os_family }}.yml'
      loop_control:
        loop_var: install_task
  become: true
