---
- name: Perform install from artifacts
  block:
    - name: Install requirements
      package:
        name: >-
          {{ java_package_requirements
            | union(java_extra_package_requirements) | unique }}
        state: present
      register: installed_packages
      retries: 10
      delay: 5
      until: installed_packages is succeeded
      when: transport != 'repositories'

    - name: 'Perform {{ java_binary_type }} install'
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      with_first_found:
        - files:
          - '{{ java_distribution }}_{{ java_binary_type }}.yml'
          - '{{ java_binary_type }}.yml'
          - '{{ ansible_os_family }}.yml'
          paths:
          - tasks/Linux/install
  become: true
