---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: azure
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-azure-windows2016-sapmachine-tarball-13
    platform: windows2016core
    vm_size: Standard_D2s_v3
    assign_public_ip: true
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - windows
      - sapmachine
      - jdk
      - sapmachine_fallback
      - ver13

  - name: test-azure-windows2019-sapmachine-tarball-11
    platform: windows2019core
    vm_size: Standard_D2s_v3
    assign_public_ip: true
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - windows
      - sapmachine
      - jre
      - sapmachine_fallback
      - ver11

# todo: enable after fix!
  - name: test-azure-windows2019-sapmachine-chocolatey-13
    platform: windows2019core
    vm_size: Standard_D2s_v3
    assign_public_ip: true
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - windows
      - sapmachine
      - ver13
      - chocolatey

provisioner:
  name: ansible
  log: false
  inventory:
    group_vars:
      sapmachine:
        java_distribution: sapmachine
      ver11:
        java_major_version: 11
        java_minor_version: 0.3
      ver13:
        java_major_version: 13
      sapmachine_fallback:
        transport: fallback
      chocolatey:
        transport: chocolatey
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
        ansible_connection: winrm
  playbooks:
    create: ../resources/provisioning/AZURE/create.yml
    destroy: ../resources/provisioning/AZURE/destroy.yml
    verify: ../resources/tests/verify_win.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
scenario:
  name: cloud-azure-sapmachine-windows
verifier:
  name: ansible
  lint:
    name: ansible-lint
