---
- name: 'Perform {{ java_binary_type }} install'
  include_tasks: '{{ install_task }}'
  with_first_found:
    - 'install/{{ java_distribution }}_{{ java_binary_type }}.yml'
    - 'install/{{ java_binary_type }}.yml'
  loop_control:
    loop_var: install_task

- name: Find java_folder
  win_find:
    paths: '{{ java_path }}'
    recurse: false
    file_type: directory
    patterns: '{{ java_folder }}'
    use_regex: true
  register: java_dir

- name: Find java_folders
  win_find:
    paths: '{{ java_path }}'
    recurse: true
  register: java_dirs

- name: Set actual java directory
  set_fact:
    java_act_path: "{{ java_dir.files | map(attribute='path') | list | last }}"

- name: Set java environment variable
  win_environment:
    name: JAVA_HOME
    state: present
    value: '{{ java_act_path }}'
    level: machine

- name: Ensure that 'JAVA_HOME\bin' present in 'Path' variable
  win_path:
    elements: '{{ java_act_path }}\bin'
    state: present
    scope: machine
