---
- name: Set parse variables based on java distribution
  include_vars: java_parts.yml

- name: 'Perform {{ java_binary_type }} install'
  include_tasks: '{{ install_task }}'
  with_first_found:
    - 'install/{{ java_distribution }}_{{ java_binary_type }}.yml'
    - 'install/{{ java_binary_type }}.yml'
  loop_control:
    loop_var: install_task

- name: Finalize binary paths
  include_tasks: finalize_paths.yml
