---
- name: Set base variables based on java distribution
  include_vars: '{{ java_distribution }}_vars.yml'

- name: 'Fetch oracle artifact with {{ transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - 'fetch/{{ transport }}.yml'
    - fetch/unknown-transport.yml
  loop_control:
    loop_var: transport_driver

- name: Set parse variables based on java distribution
  include_vars: java_parts.yml
  when: java_binary_type != 'chocolatey'

- name: debug java_path
  debug:
    var: java_path

- name: 'Perform {{ java_binary_type }} install'
  include_tasks: '{{ ansible_system }}/install/{{ java_binary_type }}.yml'

- name: debug java_path
  debug:
    var: java_path

- name: debug java_folder
  debug:
    var: java_folder

- name: debug file_downloaded
  debug:
    var: file_downloaded

- name: debug java_artifact_basename
  debug:
    var: java_artifact_basename

- name: debug java_major_version
  debug:
    var: java_major_version

- name: debug java_minor_version
  debug:
    var: java_minor_version

- name: Find java_folder
  win_find:
    paths: '{{ java_path }}'
    recurse: false
    file_type: directory
    patterns: '{{ java_folder }}'
    use_regex: true
  register: java_dir

- name: debug java_dir
  debug:
    var: java_dir

- name: Set actual java directory
  set_fact:
    java_act_path: "{{ java_dir.files | map(attribute='path') | list | last }}"

- name: Set java environment variable
  win_environment:
    name: JAVA_HOME
    state: present
    value: '{{ java_act_path }}'
    level: machine

- name: Ensure that 'JAVA_HOME\bin' present in 'Path' variable
  win_path:
    elements: '{{ java_act_path }}\bin'
    state: present
    scope: machine
