---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-windows2016-sapjvm-8
    aws_image_id: ami-00a20f508263efd30
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - sapjvm

  - name: test-aws-windows2019-sapjvm-8
    aws_image_id: ami-0477b9335a5a75438
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5.large
    assign_public_ip: false
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    groups:
      - windows
      - sapjvm

provisioner:
  name: ansible
  log: false
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      sapjvm:
        java_distribution: sapjvm
        transport: sapjvm-fallback
        java_major_version: 8
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows-sapjvm-8
verifier:
  name: testinfra
  lint:
    name: flake8
