---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not ((lookup('env', 'MOLECULE_DEBUG') | bool) or (molecule_yml.provisioner.log | default(false) | bool)) }}"
  tasks:

    - name: Get instances list
      ec2_instance_facts:
        filters:
          "tag:instance": "{{ molecule_yml.platforms | map(attribute='name') | list }}"
      register: ec2_sets

    - name: Destroy molecule instance(s)
      ec2:
        state: absent
        instance_ids: "{{ ec2_sets.instances | map(attribute='instance_id') | list }}"
        wait: True
      register: server
      when: ( ec2_sets.instances | map(attribute='instance_id') | list | length )
      # async: 7200
      # poll: 0

    # - name: Wait for instance(s) deletion to complete
    #   async_status:
    #     jid: "{{ server.ansible_job_id }}"
    #   register: ec2_jobs
    #   until: ec2_jobs.finished
    #   retries: 300
    #   delay: 20
    #   loop: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: '{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}'
        dest: '{{ molecule_instance_config }}'
      when: server.changed | bool
