---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-sapmachine-jdk-tarball-13
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: true
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - sapmachine
      - jdk
      - sapmachine_fallback
      - pip2

  - name: test-aws-centos8-sapmachine-jre-tarball-13
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: t3.medium
    region: us-east-1
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: true
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - sapmachine
      - jre
      - sapmachine_fallback
      - pip3

  - name: test-aws-Debian9-sapmachine-jre-tarball-13
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: true
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - sapmachine
      - jre
      - sapmachine_fallback
      - pip2

  - name: test-aws-ubuntu18-sapmachine-jdk-tarball-13
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: true
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - sapmachine
      - jdk
      - sapmachine_fallback
      - pip3

  - name: test-aws-amazon2-sapmachine-s3-13
    image: ami-0b898040803850657
    platform: amazon2
    profile_name: epmldi-instance-profile
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: true
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ec2-user
    groups:
      - amazon_family
      - sapmachine
      - s3
      - pip2

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      sapmachine:
        java_distribution: sapmachine
        java_major_version: 13
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      sapmachine_fallback:
        transport: fallback
      s3:
        transport: s3
        transport_s3_bucket: java-molecule-s3-test
        transport_s3_path: /java/sapmachine/sapmachine-jdk-13.0.1_linux-x64_bin.tar.gz
        transport_s3_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        transport_s3_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      pip2:
        pip_executable: pip
        python_executable: python
      pip3:
        pip_executable: pip3
        python_executable: python3
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-sapmachine-13/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-sapmachine-13
verifier:
  name: ansible
  lint:
    name: ansible-lint
