---
- name: Download security policy artifact from Oracle OTN
  win_get_url:
    url: '{{ fallback_oracle_security_policy_artifacts[java_major_version|int] }}'
    dest: >-
      {{ java_download_path }}\{{ (fallback_oracle_security_policy_artifacts[java_major_version|int]
        | urlsplit('path')).split('/')[-1] }}
    headers:
      Cookie: 'oraclelicense=accept-securebackup-cookie'
    force: false
  register: policy_file_downloaded
  retries: 15
  delay: 5
  until: policy_file_downloaded is succeeded

- name: Downloaded security policy artifact
  set_fact:
    security_policy_java_artifact: '{{ policy_file_downloaded.dest }}'
