---
- name: Download security policy artifact from web
  win_get_url:
    url: '{{ java_unlimited_policy_url }}'
    dest: >-
      {{ java_download_path }}\{{ (java_unlimited_policy_url
        | urlsplit('path')).split('/')[-1] }}
    force: false
  register: policy_file_downloaded
  retries: 3
  delay: 2
  until: policy_file_downloaded is succeeded

- name: Downloaded security policy artifact
  set_fact:
    security_policy_java_artifact: '{{ policy_file_downloaded.dest }}'
