---
- name: 'Download artifact from {{ artifact_url }}'
  win_get_url:
    url: '{{ artifact_url }}'
    dest: '{{ download_path }}\{{ artifact_basename }}'
    force: true

- name: Get SHA256 checksum of file
  win_stat:
    path: '{{ download_path }}\{{ artifact_basename }}'
    get_checksum: true
    checksum_algorithm: sha256
  register: artifact
