---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-ansible-role-java-11-s3
    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - tarball_s3

  # - name: test-aws-centos6-ansible-role-java-11-s3-rpm
  #   image: ami-1585c46a
  #   instance_type: m4.large
  #   region: us-east-1
  #   vpc_subnet_id: subnet-05a2ef2b767afec50
  #   assign_public_ip: False
  #   spot_price: 0.04
  #   security_group_name:
  #     - default
  #   wait_timeout: 1800
  #   ssh_user: centos
  #   groups:
  #    - rhel_family
  #    - s3
  #    - package

  # - name: test-aws-ubuntu18-ansible-role-java-11-s3-deb
  #   image: ami-012fd5eb46f56731f
  #   instance_type: m5.large
  #   region: us-east-1
  #   vpc_subnet_id: subnet-05a2ef2b767afec50
  #   assign_public_ip: False
  #   spot_price: 0.04
  #   security_group_name:
  #     - default
  #   wait_timeout: 1800
  #   ssh_user: ubuntu
  #   groups:
  #     - debian_family
  #     - s3
  #     - package

  - name: test-aws-Debian9-ansible-role-java-11-web-tb
    image: ami-003f19e0e687de1cd
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: False
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - web
      - tarball

provisioner:
  name: ansible
  log: False
  inventory:
    group_vars:
      web:
        transport: web
        transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-11.0.2_linux-x64_bin.tar.gz"
      tarball:
        java_tarball_install: True
      tarball_s3:
        java_tarball_install: True
        transport: s3
        transport_s3_bucket: java-molecule-s3-test
        transport_s3_path: /java/11/jdk-11.0.3_linux-x64_bin.rpm
        transport_s3_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        transport_s3_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      package:
        java_tarball_install: False

  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-direct-11/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-direct-11
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
