---
- name: Test blob
  hosts: localhost
  tasks:
    - name: get java artifact
      azure_rm_storageblob:
        resource_group: epm-ldi
        storage_account_name: storage11490
        container: oracle-java
        blob: jdk-8u45-windows-x64.exe
        dest: /tmp/jdk-8u45-windows-x64.exe

    - name: Create scale set
      azure_rm_resource:
        resource_group: epm-ldi
        provider: compute
        resource_type: virtualmachinescalesets
        resource_name: myVmss
        body: >-
          {
            "sku": {
              "tier": "Standard",
              "capacity": 1,
              "name": "Standard_D2s_v3"
            },
            "properties": {
              "overprovision": true,
              "upgradePolicy": {
                "mode": "Automatic"
              },
              "virtualMachineProfile": {
                "priority":"Low",
                "storageProfile": {
                  "imageReference": {
                    "sku": "18.04-LTS",
                    "publisher": "Canonical",
                    "version": "latest",
                    "offer": "UbuntuServer"
                  },
                  "osDisk": {
                    "caching": "ReadWrite",
                    "managedDisk": {
                      "storageAccountType": "Standard_LRS"
                    },
                    "createOption": "FromImage"
                  }
                },
                "osProfile": {
                  "computerNamePrefix": "myVmss",
                  "adminUsername": "vm-admin",
                  "adminPassword": "$P@$Sw0rd_cool"
                },
                "networkProfile": {
                  "networkInterfaceConfigurations": [
                    {
                      "name": "myVmss",
                      "properties": {
                        "primary": true,
                        "enableIPForwarding": true,
                        "ipConfigurations": [
                          {
                            "name": "myVmss",
                            "properties": {
                              "subnet": {
                                "id": "/subscriptions/0cfbdd57-0340-4c6d-a3f0-91c618995c6e/resourceGroups/epm-ldi/providers/Microsoft.Network/virtualNetworks/epm-ldi-northeurope-vnet"
                              },
                              "networkSecurityGroup": {
                                "id": "/subscriptions/0cfbdd57-0340-4c6d-a3f0-91c618995c6e/resourceGroups/epm-ldi/providers/Microsoft.Network/networkSecurityGroups/epm-ldi-northeurope-sg"
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            },
            "location": "northeurope"
          }

# - name: Converge
#   hosts: all
  # roles:
  #   - role: ansible-role-java
