---
- name: Converge
  hosts: all
  pre_tasks:
    - name: get java artifact
      azure_rm_storageblob:
        resource_group: epm-ldi
        storage_account_name: storage11490
        container: oracle-java
        blob: jdk-8u45-windows-x64.exe
        dest: /tmp/jdk-8u45-windows-x64.exe
  roles:
    - role: ansible-role-java
