---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-java
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-6u45-linux-x64.tar.gz"
      java_unlimited_policy_enabled: True
